### ISSUE TITLE
[iOS] Resizing issue for animating streams

### ISSUE THREAD

**Issue by terrychen1122** [Azure/Communication#262]
Summary
When animating the size & position of a stream, the size change doesn't respect the animation. It just becomes the end size immediately. It happens to both local and remote streams. We don't see the same issue on Android, iOS only. 

1. Have a container view to hosting the stream as its subview (probably set the background color of the container a different color than the screen)
2. Use either manual layout or auto layout for the stream view
3. Animate size change of the container view
4. When making it bigger, the stream immediately becomes the end size and it can see it not animate along with the container. It's just like the container is becoming bigger and revealing the stream. When making it smaller, same thing happens. Now, the stream becomes small immediately and the container is shrinking.

Expected
The stream should be animated along with the container.

Video
https://user-images.githubusercontent.com/5403473/115479005-49633100-a1fc-11eb-8a3f-3f5fd7fd7f2f.mov
[You can scrub the video by looking at it frame by frame]

Configuration
- Version of the release: beta 9
- iOS: 14+
- Device: iPhone 11 Pro

Additional context
Not a hard blocker on video calling experience, but it really makes our UX not delightful and we should address it soon.

**Comment by sankum-msft** [comment]
Thanks for reporting. I've opened AB#2428827 to track it.

**Comment by mariusu-msft** [comment]
This is fixed in latest release.

**Comment by ryanespiritu** [comment]
Thanks @mariusu-msft! What is the release version you are referring too. I'm still experiencing the issue on `1.1.0-beta.1`, however it looks like from the [bug fix notes](https://github.com/Azure/Communication/releases/tag/v1.1.0-beta.1) this should have been resolved in this version. Note, I haven't had the chance to verify things on the newest release (`2.0.0-beta.1`) yet because of this [build issue](https://github.com/Azure/Communication/issues/344). Thanks

**Comment by mariusu-msft** [comment]
Reopening issue.

**Comment by raosanat** [comment]
@ryanespiritu I have replied with a solution to the build issue in the other GitHub issue, please verify with the latest beta version and we will investigate if issue is still reproducible in that.

**Comment by ryanespiritu** [comment]
Just verified that this is still happening for me on `2.0.1.-beta.1`

https://user-images.githubusercontent.com/71148942/135899977-89134165-2005-45ed-b217-98b5048a62ad.mov
